import {MigrationInterface, QueryRunner} from 'typeorm';

export class CreateEmDoctosTable1513612207705 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`create table Dados.EmDoctos(
            doc_num_proposta int identity not null primary key,
            doc_prop_apolice int not null,
            doc_tipo_movto varchar(2) not null,
            cli_codigo int not null,
            cia_codigo int null,
            ramo_codigo int not null,
            pto_codigo int not null,
            doc_apolice varchar(30) null,
            doc_endosso varchar(30) null,
            doc_data_proposta datetime null,
            doc_data_emissao datetime null,
            doc_data_entrada datetime null,
            doc_inicio_vigencia datetime null,
            doc_final_vigencia datetime null,
            doc_qtd_parcelas int null,
            doc_situacao varchar(1) null,
            doc_renov_numero varchar(30) null,
            cia_codigo_renov int null,
            doc_anotacoes text null,
            doc_comiss_adic varchar(1) null,
            doc_prop_ult_mov int null,
            doc_tipo_comiss varchar(1) null,
            doc_agencia_debito varchar(10) null,
            doc_primeiraavista varchar(1) null,
            cli_codigo_estipulante int null,
            doc_forma_pagamento varchar(1) null,
            cli_codigo_subestipulante int null,
            doc_renovacao_interna varchar(1) null,
            doc_controle varchar(30) null,
            doc_prop_cancelada varchar(25) null,
            doc_bonus_indicacao numeric(15, 2) null,
            ciareg_codigo int null,
            moeda_codigo int null,
            doc_premio_liquido numeric(15, 2) null,
            cotac_data datetime null,
            doc_adicional_frac numeric(15, 2) null,
            doc_custo numeric(15, 2) null,
            cli_codigo_indicacao int null,
            doc_iof numeric(15, 2) null,
            doc_premio_total numeric(15, 2) null,
            doc_data_envio_proposta datetime null,
            doc_perc_comissao numeric(15, 4) null,
            estrut_codigo int null,
            doc_perc_comissao_extra numeric(15, 4) null,
            doc_comissao numeric(15, 2) null,
            sitren_codigo int null,
            doc_perc_comissao_total numeric(15, 4) null,
            doc_data_distrenov datetime null,
            doc_desc_comissao numeric(15, 4) null,
            rrep_codigo int null,
            doc_mes_base_renovacao varchar(7) null,
            doc_conta_debito varchar(25) null,
            doc_tipo_apolice varchar(2) null,
            doc_premio_servico_adic numeric(15, 2) null,
            doc_endosso2 varchar(30) null,
            doc_apolice2 varchar(30) null,
            doc_primeira_parcela int null,
            tpmov_codigo int null,
            bco_codigo_debito int null,
            aud_inclusao_usr varchar(50) null,
            aud_inclusao_data datetime null,
            aud_alteracao_usr varchar(50) null,
            aud_alteracao_data datetime null,
            doc_tipo6 varchar(1) null,
            doc_num_proposta6 int null,
            doc_comissao_original numeric(15, 2) null,
            flg_prob_endosso varchar(1) null,
            numpedido int null,
            numsequencia int null,
            doc_codigo_origem varchar(60) null,
            doc_identificacao varchar(50) null,
            doc_intervalo_venc int null,
            doc_arquivo_numero varchar(20) null,
            doc_sigiloso varchar(1) null,
            doc_premio_liquido_original numeric(15, 2) null,
            doc_adicional_frac_original numeric(15, 2) null,
            doc_livro_numero_susep int null,
            doc_livro_pagina_susep int null,
            doc_livro_registro_susep int null,
            cia_codigo_original int null,
            pto_codigo_original int null,
            ramo_codigo_original int null,
            vend_codigos_original varchar(20) null,
            cco_codigos_original varchar(20) null,
            docori_codigo int null,
            cn_codigo int null,
            clidiv_codigo int null,
            doc_data_recusa datetime null,
            tpmov_codigo_recusa int null,
            doc_cedente_boleto int null,
            doc_codigo_negociacao varchar(50) null,
            doc_dia_vencimento int null,
            doc_comiss_outros_servicos varchar(1) null,
            doc_num_prop_renovada int null,
            doc_geracao_automatica varchar(1) null
        )`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`drop table Dados.EmDoctos;`);
    }

}
